In [119]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB

In [6]:
# Loading dataset
df = pd.read_csv("Bank.csv")
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [26]:
df.describe()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,93152.503000,2.396400,1.937938,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852197,1.147663,1.747659,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [10]:
# Checking for missing values
missing_values = df.isnull().sum()
missing_values

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [12]:
# Checking for duplicate rows in the dataset
duplicates = df.duplicated().sum()
duplicates

0

In [14]:
# Dropping ID and ZIP Code, columns
df2 = df.drop(columns=['ID', 'ZIP Code'])
df2.head()

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1

In [38]:
# Define features and target
X = df2.drop(columns=['Personal Loan'])
y = df2['Personal Loan']

In [40]:
# Convert categorical variables with more than two categories into dummy variables
X = pd.get_dummies(X, drop_first=True)

In [42]:
# Split data into training (60%) and validation (40%) sets
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.4, random_state=42)

In [44]:
# Standardize the feature data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)

In [46]:
# Define the KNN classifier with k=1
knn = KNeighborsClassifier(n_neighbors=1)

In [48]:
# Train the model
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=1)

In [ ]:
# KNN PROBLEM

In [ ]:
# (a)

In [50]:
# Define the new customer for classification
new_customer = pd.DataFrame({
    'Age': [40], 'Experience': [10], 'Income': [84], 'Family': [2], 'CCAvg': [2], 
    'Education_1': [0], 'Education_2': [1], 'Education_3': [0], 'Mortgage': [0], 
    'Securities Account': [0], 'CD Account': [0], 'Online': [1], 'Credit Card': [1]
})

In [52]:
# Convert categorical variables into dummy variables
new_customer = pd.get_dummies(new_customer)

In [54]:
# Ensuring new_customer has the same columns as X_train
new_customer = new_customer.reindex(columns=X_train.columns, fill_value=0)

In [56]:
# Standardize the new customer data
new_customer_scaled = scaler.transform(new_customer)

In [60]:
# Predict the classification for the new customer
prediction = knn.predict(new_customer_scaled)
prediction

array([0], dtype=int64)

In [ ]:
# (b)

In [ ]:
# b. What is a choice of k that balances between overfitting and ignoring the predictor information?

In [64]:
# Test different values of k to find the one that balances between overfitting and ignoring predictor information
best_k = 1
best_accuracy = 0

# Iterate over a range of k values (e.g., 1 to 20) to find the best k
for k in range(1, 21):
    # Define the KNN classifier with the current k
    knn = KNeighborsClassifier(n_neighbors=k)
    
    # Train the model
    knn.fit(X_train_scaled, y_train)
    
    # Predict on the validation data
    y_pred = knn.predict(X_valid_scaled)
    
    # Calculate the accuracy on the validation data
    accuracy = accuracy_score(y_valid, y_pred)
    
    # Update the best k if the current accuracy is better
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_k = k

best_k

1

In [ ]:
# (c) 
# c. Show the confusion matrix for the validation data that results from using the best k

In [68]:
# Define the KNN classifier with the best k value (which was found to be 1)
knn = KNeighborsClassifier(n_neighbors=best_k)

# Training the model with the best k
knn.fit(X_train_scaled, y_train)

# Predicting on the validated data using the best k
y_valid_pred = knn.predict(X_valid_scaled)

# Generate the confusion matrix for the validation data
conf_matrix = confusion_matrix(y_valid, y_valid_pred)

print(conf_matrix)

[[1782   17]
 [  66  135]]

In [ ]:
# (d)
'''
Consider the following customer: Age = 40, Experience = 10, Income = 84, Family= 2,
CCAvg = 2, Education_1 = 0, Education_2 = 1, Education_3 = 0, Mortgage = 0, Securities
Account = 0, CD Account = 0, Online = 1 and Credit Card = 1. Classify the customer using the
best k.
'''

In [70]:
# Predict the classification for the new customer using the best k
best_k_prediction = knn.predict(new_customer_scaled)

# Output the prediction
best_k_prediction

array([0], dtype=int64)

In [74]:
# evaluating the accuracy of the prediction
best_k_accuracy = accuracy_score(y_valid, y_valid_pred)
best_k_accuracy

0.9585

In [ ]:
# NBC PROBLEM

In [76]:
df_nbc = pd.read_csv("Bank.csv")

In [78]:
# Dropping ID and ZIP Code, columns
df_nbc= df.drop(columns=['ID', 'ZIP Code'])
df_nbc.head()

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1

In [86]:
# Splitting the data into training (60%) and validation (40%) sets
X_nbc = df_nbc.drop(columns=['Personal Loan'])
y_nbc = df_nbc['Personal Loan']
X_train_nbc, X_valid_nbc, y_train_nbc, y_valid_nbc = train_test_split(X_nbc, y_nbc, test_size=0.4, random_state=42)

In [88]:
# Using the pandas dataframe methods melt() and pivot()

# Melting the dataset with relevant columns only
melted_data = pd.melt(
    X_train_nbc.assign(Personal_Loan=y_train_nbc),
    id_vars=['CreditCard', 'Online', 'Personal_Loan']
)

# Create the pivot table from the melted data using 'Online' as columns, 'CreditCard' as rows, and 'Personal Loan' as secondary rows (count)
pivot_table_nbc = X_train_nbc.assign(Personal_Loan=y_train_nbc).pivot_table(
    index=['CreditCard', 'Personal_Loan'],
    columns='Online',
    aggfunc='size',
    fill_value=0
)

# Viewing the table
pivot_table_nbc

Online                      0     1
CreditCard Personal_Loan
0          0              780  1141
           1               70   129
1          0              319   481
           1               34    46

In [ ]:
# (b)
'''
Consider the task of classifying a customer who owns a bank credit card and is actively using
online banking services. Looking at the pivot table, what is the probability that this customer will
accept the loan offer? [This is the probability of loan acceptance (Loan = 1) conditional on
having a bank credit card (CC = 1) and being an active user of online banking services (Online =
1).]
'''

In [90]:
# The customer owns a credit card (CC = 1) and is actively using online banking services (Online = 1)
credit_card = 1
online = 1

# Extract the count of customers with CreditCard = 1, Online = 1, and Loan = 1 (accepted)
loan_accepted = pivot_table_nbc.loc[(credit_card, 1), online]

# Extract the count of customers with CreditCard = 1, Online = 1 (total customers with CreditCard = 1 and Online = 1)
total_customers = pivot_table_nbc.loc[(credit_card,), online].sum()

# Calculate the conditional probability
probability_loan_acceptance = loan_accepted / total_customers

probability_loan_acceptance

0.0872865275142315

In [ ]:
# c
'''
Create two separate pivot tables for the training data. One will have Loan (rows) as a function
of Online (columns) and the other will have Loan (rows) as a function of CC
'''

In [102]:
# Create two separate pivot tables for the training data
# One with Loan (rows) as a function of Online (columns)
pivot_table_online = X_train_nbc.assign(Personal_Loan=y_train_nbc).pivot_table(
    index='Personal_Loan',
    columns='Online',
    aggfunc='size',
    fill_value=0
)

# One with Loan (rows) as a function of Credit Card (columns)
pivot_table_cc = X_train_nbc.assign(Personal_Loan=y_train_nbc).pivot_table(
    index='Personal_Loan',
    columns='CreditCard',
    aggfunc='size',
    fill_value=0
)

# Display both pivot tables to the user
print("Pivot Table 1 (Loan vs Online):\n")
print(pivot_table_online)
print("\nPivot Table 2 (Loan vs Credit Card):\n")
print(pivot_table_cc)

Pivot Table 1 (Loan vs Online):

Online            0     1
Personal_Loan
0              1099  1622
1               104   175

Pivot Table 2 (Loan vs Credit Card):

CreditCard        0    1
Personal_Loan
0              1921  800
1               199   80

In [ ]:
# (d)
'''
d. Compute the following quantities [P(A ∣ B) means “the probability of A givenB”]:
i. P(CC = 1 ∣ Loan = 1) (the proportion of credit card holders among the loan acceptors)
ii. P(Online = 1 ∣ Loan = 1)
iii. P(Loan = 1) (the proportion of loan acceptors)
iv. P(CC = 1 ∣ Loan = 0)
v. P(Online = 1 ∣ Loan = 0)
vi. P(Loan = 0)
'''

In [106]:
# Calculating the probabilities
P_CC_given_Loan_1 = pivot_table_cc.loc[1, 1] / pivot_table_cc.loc[1].sum()
P_Online_given_Loan_1 = pivot_table_online.loc[1, 1] / pivot_table_online.loc[1].sum()
P_Loan_1 = y_train_nbc.mean()  # Assuming y_train_nbc is a binary Series
P_CC_given_Loan_0 = pivot_table_cc.loc[0, 1] / pivot_table_cc.loc[0].sum()
P_Online_given_Loan_0 = pivot_table_online.loc[0, 1] / pivot_table_online.loc[0].sum()
P_Loan_0 = 1 - P_Loan_1

# Print the calculated probabilities
print("P(CC=1 | Loan=1):", P_CC_given_Loan_1)
print("P(Online=1 | Loan=1):", P_Online_given_Loan_1)
print("P(Loan=1):", P_Loan_1)
print("P(CC=1 | Loan=0):", P_CC_given_Loan_0)
print("P(Online=1 | Loan=0):", P_Online_given_Loan_0)
print("P(Loan=0):", P_Loan_0)

P(CC=1 | Loan=1): 0.2867383512544803
P(Online=1 | Loan=1): 0.6272401433691757
P(Loan=1): 0.093
P(CC=1 | Loan=0): 0.29400955531054757
P(Online=1 | Loan=0): 0.5961043733921353
P(Loan=0): 0.907

In [ ]:
# (e)
'''
 Use the quantities computed above to compute the naive Bayes probability
P(Loan = 1 ∣ CC = 1, Online = 1)
'''

In [113]:
# Bayes rule: P(Loan = 1 | CC = 1, Online = 1) = P(CC = 1 | Loan = 1) * P(Online = 1 | Loan = 1) * P(Loan = 1) / P(CC = 1, Online = 1)

# Calculate P(CC = 1, Online = 1) for normalization (combining both loan and non-loan acceptors)
P_CC_1_Online_1 = (
    P_CC_given_Loan_1 * P_Online_given_Loan_1 * P_Loan_1 +
    P_CC_given_Loan_0 * P_Online_given_Loan_0 * P_Loan_0
)

# Calculate the naive Bayes probability P(Loan = 1 | CC = 1, Online = 1)
P_Loan_1_given_CC_1_Online_1 = (
    P_CC_given_Loan_1 * P_Online_given_Loan_1 * P_Loan_1
) / P_CC_1_Online_1

print("P(Loan=1 | CC=1, Online=1):", P_Loan_1_given_CC_1_Online_1)

P(Loan=1 | CC=1, Online=1): 0.09520539112336063

In [ ]:
# (f)
'''
Compare this value with the one obtained from the pivot table in (b). Which is a more accurate
estimate?
'''

In [117]:
# Comparing the probability obtained from the pivot table in (b) and the naive Bayes probability obtained in (e)

# Probability from pivot table (part b)
probability_pivot_table = probability_loan_acceptance

# Naive Bayes probability (part e)
probability_naive_bayes = P_Loan_1_given_CC_1_Online_1

# Calculate the difference between the two probabilities
difference = abs(probability_pivot_table - probability_naive_bayes)

print("Probability from Pivot Table:", probability_pivot_table)
print("Naive Bayes Probability:", probability_naive_bayes)
print("Difference between the two:", difference)

Probability from Pivot Table: 0.0872865275142315
Naive Bayes Probability: 0.09520539112336063
Difference between the two: 0.007918863609129134

In [ ]:
'''
In this case, the pivot table probability (8.73%) is likely a more accurate estimate of loan acceptance for the given conditions within the dataset because it directly represents the observed data.
The naive Bayes estimate (9.52%) assumes conditional independence, which may not perfectly hold between features like CreditCard and Online usage
'''

In [ ]:
# (g)
'''
Which of the entries in this table are needed for computing P(Loan = 1 ∣ CC = 1, Online = 1)?
In Python, run naive Bayes on the data. Examine the model output on training data, and find the
entry that corresponds to P(Loan = 1 ∣ CC = 1, Online = 1). Compare this to the number you
obtained in (e).
'''

In [123]:
# Prepare the data for Naive Bayes model training
# Convert categorical variables with more than two categories into dummy variables
X_nbc_encoded = pd.get_dummies(X_nbc, drop_first=True)

# Split the encoded data into training and validation sets
X_train_nbc_encoded, X_valid_nbc_encoded, y_train_nbc_encoded, y_valid_nbc_encoded = train_test_split(X_nbc_encoded, y_nbc, test_size=0.4, random_state=42)

# Instantiate the Naive Bayes classifier
nb_classifier = GaussianNB()

# Train the model
nb_classifier.fit(X_train_nbc_encoded, y_train_nbc_encoded)

# Predict probabilities for the validation set
y_valid_probs = nb_classifier.predict_proba(X_valid_nbc_encoded)

In [125]:
# Extract the probability P(Loan = 1 | CC = 1, Online = 1) from the model output for customers with CC = 1 and Online = 1
# Filter the validation set for customers with CC = 1 and Online = 1
filter_condition = (X_valid_nbc_encoded['CreditCard'] == 1) & (X_valid_nbc_encoded['Online'] == 1)
filtered_probs = y_valid_probs[filter_condition.values]

# Calculate the average probability of Loan = 1 for the filtered customers
average_prob_loan_1 = filtered_probs[:, 1].mean()

# Output the average probability
average_prob_loan_1

0.25615369840924535